### ISSUE TITLE
How to set the Datadog hostname and service name?

### ISSUE THREAD

**Issue by gitSambhal** [theogravity/pino-datadog-transport#11]
<img width="478" alt="Screenshot 2022-09-27 at 9 58 35 AM" src="https://user-images.githubusercontent.com/15196655/192432266-a9aad9d2-01cc-4758-b2b8-d1d1e3d2108e.png">

I have DD_SERVICE and DD_SERVICE_NAME environment variables defined but the Datadog logs are not showing the service name. I am using this transport with [Pino NestJS](https://www.npmjs.com/package/nestjs-pino). When I use the Winston Nestjs then I am able to see the correct service name and host. How can I set these hostname and service name fields?

**Comment by theogravity** [comment]
Searching for the env variable in the `datadog-api-client-typescript` project (which is what this project uses), I don't see any direct reference outside of unit tests for `DD_SERVICE` and none at all for `DD_SERVICE_NAME`.

 https://github.com/DataDog/datadog-api-client-typescript/search?q=DD_SERVICE

It's possible that whoever wrote the winston transport for datadog added this support in.

I would welcome a PR where if the `ddsource` and / or `ddtags` config items aren't set, then fallback to the env variables if defined.

**Comment by gitSambhal** [comment]
@theogravity ddsource and service is given in the config but even then it is not showing in Datadog.
<img width="423" alt="Screenshot 2022-09-27 at 3 27 14 PM" src="https://user-images.githubusercontent.com/15196655/192496071-3b2cbad8-ffda-4f40-9c96-5491e5d3387e.png">

**Comment by gitSambhal** [comment]
> @theogravity ddsource and service is given in the config but even then it is not showing in Datadog. <img alt="Screenshot 2022-09-27 at 3 27 14 PM" width="423" src="https://user-images.githubusercontent.com/15196655/192496071-3b2cbad8-ffda-4f40-9c96-5491e5d3387e.png">

Got it working. `ddsource` and `service` should be inside options instead of `ddClientConf`

```
  const ddTransportConfigEU: TransportTargetOptions = {
    level,
    options: {
      ddClientConf: {
        authMethods: {
          apiKeyAuth: env.DD_API_KEY,
        },
        ddServerConf: { site: env.DD_SITE },
      },
      ddsource: 'nodejs',
      service: env.DD_SERVICE,
    },
    target: 'pino-datadog-transport',
  };
```

**Comment by theogravity** [comment]
Sorry you had to go through that. Their config / SDK is kind of a mess.

**Comment by gitSambhal** [comment]
@theogravity Is there any way to change the host name in Datadog? I tried giving `DD_HOST` and `DD_HOSTNAME` in `.env` file but it didn't work.

![image](https://user-images.githubusercontent.com/15196655/203500686-e00c8041-9602-4b3b-b729-dc7d8a98be83.png)

**Comment by theogravity** [comment]
> @theogravity Is there any way to change the host name in Datadog? I tried giving `DD_HOST` and `DD_HOSTNAME` in `.env` file but it didn't work.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/15196655/203500686-e00c8041-9602-4b3b-b729-dc7d8a98be83.png)
> 
> 

If you replace the search above with DD_HOST, there's no reference to it.

I'd post an issue in that repo asking how to change that.

It could also be this is purely pino-derived and has nothing to do with this plugin but is something you'd configure in pink itself.

**Comment by gitSambhal** [comment]
> 

Yeah,  please share the issue link with me too once created.

**Comment by theogravity** [comment]
> > 
> 
> 
> 
> Yeah,  please share the issue link with me too once created.

Please create it yourself, using the prior issue ticket as an example.

**Comment by gitSambhal** [comment]
> > > 
> > 
> > 
> > Yeah,  please share the issue link with me too once created.
> 
> Please create it yourself, using the prior issue ticket as an example.

https://github.com/DataDog/datadog-api-client-typescript/issues/928
