### ISSUE TITLE
Export the type DDTransportOptions

### ISSUE THREAD

**Issue by gitSambhal** [theogravity/pino-datadog-transport#15]
Hi @theogravity 
Can you pls export the type `DDTransportOptions` from the package as currently nothing is exported from the package.

<img width="967" alt="image" src="https://github.com/theogravity/pino-datadog-transport/assets/15196655/e09b72b5-a0c5-4d2d-8035-d6c6fa70eb2a">

**Comment by theogravity** [comment]
> Hi @theogravity 
> 
> Can you pls export the type `DDTransportOptions` from the package as currently nothing is exported from the package.
> 
> 
> 
> <img width="967" alt="image" src="https://github.com/theogravity/pino-datadog-transport/assets/15196655/e09b72b5-a0c5-4d2d-8035-d6c6fa70eb2a">
> 
> 

Feel free to open a PR.

**Comment by gitSambhal** [comment]
I checked the current code and found that the type can be imported as follows:
```
import { DDTransportOptions } from 'pino-datadog-transport/build/process-logs';

```
