### ISSUE TITLE
Doesnt seem to play nice with google cloud functions?

### ISSUE THREAD

**Issue by cjsewell** [theogravity/pino-datadog-transport#19]
When using this package in google cloud functions, we get errors with the function not terminating. 
In google cloud console the function is forcibly terminated after 15 minutes with the error "Error: Process exited with code 143 "

Even tho the process has completed, there is something still "hanging"

I tracked it down to exit_hook. Using patch package to remove it from [process-logs.ts](https://github.com/theogravity/pino-datadog-transport/blob/master/src/process-logs.ts#L181) seemed to solve it for me....

Is exit_hook needed if sendImmediate is true?
Should this issue be opened in exit_hook instead?

Thanks!

**Comment by theogravity** [comment]
exitHook is two major versions behind since the next major is ESM only. It is probably some bug that may have been corrected later.

I'll look into seeing if there's an alternative or I just fork the thing.

But prob isn't needed if sendImmediate is true.

**Comment by theogravity** [comment]
I've pushed a new 3.0.0 version that updates the exit hook to the latest version, but also only enable it if sendImmediate is false.

If it does not fix the issue, please open an issue on:

https://github.com/theogravity/datadog-transports/issues

as I've moved the code there.
