### ISSUE TITLE
Set EU server not possible

### ISSUE THREAD

**Issue by mariuszbeltowski** [theogravity/pino-datadog-transport#5]
How to set the eu server as destination? I am getting 403 with debug on.

**Comment by theogravity** [comment]
I actually couldn't figure that out myself, which is why I exposed the entire client options. 

I created this issue with the datadog client folks:

https://github.com/DataDog/datadog-api-client-typescript/issues/802

**Comment by gitSambhal** [comment]
Logs are not being sent to the EU server even after updating the site configuration as follows
```
ddServerConf: { site: 'datadoghq.eu' }
```

I tested the same code with US server by commenting the above line and it worked.

Can you plz check and suggest the fix?
@theogravity

**Comment by theogravity** [comment]
@gitSambhal The lib is doing what the issue ticket describes I should do:

https://github.com/DataDog/datadog-api-client-typescript#changing-server

https://github.com/theogravity/pino-datadog-transport/blob/55eeaaa4ae64e664f62938f1554e9bd3ced39f21/src/index.ts#L7

I'll ask if what I'm doing is right in the issue ticket that was closed...

**Comment by gitSambhal** [comment]
Now it is working fine, not sure what was the issue. thank you @theogravity
