### ISSUE TITLE
onError deos not work

### ISSUE THREAD

**Issue by mariuszbeltowski** [theogravity/pino-datadog-transport#6]
`onError` deos not work, code below:
```  onError: (err: any, logs?: Array<Record<string, any>>) => {
    console.error('error', err, logs);
  },
```

results in:
```
error undefined undefined
```

**Comment by theogravity** [comment]
Can you give me example code that reproduces this?

**Comment by theogravity** [comment]
Going to close as I've updated the error reporting behavior. Re-open if you still have issues with some info about your configuration.
